require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PatternTypesController do

  # This should return the minimal set of attributes required to create a valid
  # PatternType. As you add validations to PatternType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatternTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pattern_types as @pattern_types" do
      pattern_type = PatternType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pattern_types).should eq([pattern_type])
    end
  end

  describe "GET show" do
    it "assigns the requested pattern_type as @pattern_type" do
      pattern_type = PatternType.create! valid_attributes
      get :show, {:id => pattern_type.to_param}, valid_session
      assigns(:pattern_type).should eq(pattern_type)
    end
  end

  describe "GET new" do
    it "assigns a new pattern_type as @pattern_type" do
      get :new, {}, valid_session
      assigns(:pattern_type).should be_a_new(PatternType)
    end
  end

  describe "GET edit" do
    it "assigns the requested pattern_type as @pattern_type" do
      pattern_type = PatternType.create! valid_attributes
      get :edit, {:id => pattern_type.to_param}, valid_session
      assigns(:pattern_type).should eq(pattern_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PatternType" do
        expect {
          post :create, {:pattern_type => valid_attributes}, valid_session
        }.to change(PatternType, :count).by(1)
      end

      it "assigns a newly created pattern_type as @pattern_type" do
        post :create, {:pattern_type => valid_attributes}, valid_session
        assigns(:pattern_type).should be_a(PatternType)
        assigns(:pattern_type).should be_persisted
      end

      it "redirects to the created pattern_type" do
        post :create, {:pattern_type => valid_attributes}, valid_session
        response.should redirect_to(PatternType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pattern_type as @pattern_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatternType.any_instance.stub(:save).and_return(false)
        post :create, {:pattern_type => { "name" => "invalid value" }}, valid_session
        assigns(:pattern_type).should be_a_new(PatternType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PatternType.any_instance.stub(:save).and_return(false)
        post :create, {:pattern_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pattern_type" do
        pattern_type = PatternType.create! valid_attributes
        # Assuming there are no other pattern_types in the database, this
        # specifies that the PatternType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PatternType.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => pattern_type.to_param, :pattern_type => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested pattern_type as @pattern_type" do
        pattern_type = PatternType.create! valid_attributes
        put :update, {:id => pattern_type.to_param, :pattern_type => valid_attributes}, valid_session
        assigns(:pattern_type).should eq(pattern_type)
      end

      it "redirects to the pattern_type" do
        pattern_type = PatternType.create! valid_attributes
        put :update, {:id => pattern_type.to_param, :pattern_type => valid_attributes}, valid_session
        response.should redirect_to(pattern_type)
      end
    end

    describe "with invalid params" do
      it "assigns the pattern_type as @pattern_type" do
        pattern_type = PatternType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatternType.any_instance.stub(:save).and_return(false)
        put :update, {:id => pattern_type.to_param, :pattern_type => { "name" => "invalid value" }}, valid_session
        assigns(:pattern_type).should eq(pattern_type)
      end

      it "re-renders the 'edit' template" do
        pattern_type = PatternType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PatternType.any_instance.stub(:save).and_return(false)
        put :update, {:id => pattern_type.to_param, :pattern_type => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pattern_type" do
      pattern_type = PatternType.create! valid_attributes
      expect {
        delete :destroy, {:id => pattern_type.to_param}, valid_session
      }.to change(PatternType, :count).by(-1)
    end

    it "redirects to the pattern_types list" do
      pattern_type = PatternType.create! valid_attributes
      delete :destroy, {:id => pattern_type.to_param}, valid_session
      response.should redirect_to(pattern_types_url)
    end
  end

end
