require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SashesController do

  # This should return the minimal set of attributes required to create a valid
  # Sash. As you add validations to Sash, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "colour" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SashesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sashes as @sashes" do
      sash = Sash.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sashes).should eq([sash])
    end
  end

  describe "GET show" do
    it "assigns the requested sash as @sash" do
      sash = Sash.create! valid_attributes
      get :show, {:id => sash.to_param}, valid_session
      assigns(:sash).should eq(sash)
    end
  end

  describe "GET new" do
    it "assigns a new sash as @sash" do
      get :new, {}, valid_session
      assigns(:sash).should be_a_new(Sash)
    end
  end

  describe "GET edit" do
    it "assigns the requested sash as @sash" do
      sash = Sash.create! valid_attributes
      get :edit, {:id => sash.to_param}, valid_session
      assigns(:sash).should eq(sash)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sash" do
        expect {
          post :create, {:sash => valid_attributes}, valid_session
        }.to change(Sash, :count).by(1)
      end

      it "assigns a newly created sash as @sash" do
        post :create, {:sash => valid_attributes}, valid_session
        assigns(:sash).should be_a(Sash)
        assigns(:sash).should be_persisted
      end

      it "redirects to the created sash" do
        post :create, {:sash => valid_attributes}, valid_session
        response.should redirect_to(Sash.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sash as @sash" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sash.any_instance.stub(:save).and_return(false)
        post :create, {:sash => { "colour" => "invalid value" }}, valid_session
        assigns(:sash).should be_a_new(Sash)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sash.any_instance.stub(:save).and_return(false)
        post :create, {:sash => { "colour" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sash" do
        sash = Sash.create! valid_attributes
        # Assuming there are no other sashes in the database, this
        # specifies that the Sash created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sash.any_instance.should_receive(:update).with({ "colour" => "MyString" })
        put :update, {:id => sash.to_param, :sash => { "colour" => "MyString" }}, valid_session
      end

      it "assigns the requested sash as @sash" do
        sash = Sash.create! valid_attributes
        put :update, {:id => sash.to_param, :sash => valid_attributes}, valid_session
        assigns(:sash).should eq(sash)
      end

      it "redirects to the sash" do
        sash = Sash.create! valid_attributes
        put :update, {:id => sash.to_param, :sash => valid_attributes}, valid_session
        response.should redirect_to(sash)
      end
    end

    describe "with invalid params" do
      it "assigns the sash as @sash" do
        sash = Sash.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sash.any_instance.stub(:save).and_return(false)
        put :update, {:id => sash.to_param, :sash => { "colour" => "invalid value" }}, valid_session
        assigns(:sash).should eq(sash)
      end

      it "re-renders the 'edit' template" do
        sash = Sash.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sash.any_instance.stub(:save).and_return(false)
        put :update, {:id => sash.to_param, :sash => { "colour" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sash" do
      sash = Sash.create! valid_attributes
      expect {
        delete :destroy, {:id => sash.to_param}, valid_session
      }.to change(Sash, :count).by(-1)
    end

    it "redirects to the sashes list" do
      sash = Sash.create! valid_attributes
      delete :destroy, {:id => sash.to_param}, valid_session
      response.should redirect_to(sashes_url)
    end
  end

end
